---
- include: configuration/update-user.yml
  vars:
    hosts: 'control'
    user: 'root'
  tags:
  - root-user

- hosts: control
  become: yes
  vars_files:
  - ~/.apigee/credentials.yml
  tasks:
  - name: Install system packages
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - python-devel
    - openssl-devel
    - gcc

  - name: Install pip
    easy_install:
      name: pip
      state: latest

  - name: Install ansible
    pip:
      name: ansible
      state: latest
    register: result

