---
- include: configuration/update-user.yml
  vars:
    hosts: '{{ hosts }}'
    user: 'root'
  tags:
  - root-user

- hosts: '{{ hosts }}'
  become: yes

  vars_files:
  - ~/.apigee/credentials.yml

  tasks:
  - name: Install system packages
    become: yes
    yum:
      name: '{{ item }}'
      state: present
    with_items:
    - python-devel
    - openssl-devel
    - gcc
    - vim
    when: ansible_os_family | lower == 'redhat'

  - name: Install pip
    become: yes
    easy_install:
      name: pip
      state: latest
    when: ansible_os_family | lower == 'redhat'

  - name: Install ansible
    become: yes
    pip:
      name: ansible
      state: latest
    register: result
    when: ansible_os_family | lower == 'redhat'

