---
- hosts: localhost
  connection: local
  vars:
    workspace: ~/apigee-workspace/opdk-workspace
    git_repo: git@github.com:carlosfrias
    git_dest: /tmp
    repositories: 
    - apigee-opdk-aws-create
    - apigee-opdk-aws-terminate
    - apigee-opdk-setup-postgres-standby
    - apigee-opdk-setup-selinux-disable
    - apigee-opdk-setup-status
    - apigee-opdk-setup-validate
    - apigee-opdk-setup-validate-cleanup
    - apigee-opdk-time-sync
  tasks:
  - name: Checkout repositories
    git:
      repo: '{{ git_repo }}/{{ item }}.git'
      dest: '{{ git_dest }}/{{ item }}'
    with_items: '{{ repositories }}'

  - name: Copy .git folder to workspace
    copy: 
      src: '{{ git_dest }}/{{ item }}/.git'
      dest: '{{ workspace  }}/{{ item }}/'
    with_items: '{{ repositories }}'

  - name: Cleanup tmp folder
    file:
      path: '{{ git_dest }}/{{ item }}'
      state: absent
    with_items: '{{ repositories }}'


