---
- hosts: localhost
  connection: local
  vars:
    workspace: ~/apigee-workspace/opdk-workspace
    git_repo: git@github.com:carlosfrias
    git_dest: /tmp
    repositories: 
    - apigee-opdk-setup-default-settings
    - apigee-opdk-setup-apigee-user
    - apigee-opdk-setup-bootstrap
    - apigee-opdk-setup-os-common
    - apigee-opdk-setup-os-limits
    - apigee-opdk-setup-os-minimum
    - apigee-opdk-setup-os-postgres
    - apigee-opdk-setup-postgres-config
    - apigee-opdk-setup-postgres-master
    - apigee-opdk-setup-postgres-standby
    - apigee-opdk-setup-silent-installation-config
    - apigee-opdk-shutdown-iptables

  tasks:
  - name: Checkout repositories
    git:
      repo: '{{ git_repo }}/{{ item }}.git'
      dest: '{{ git_dest }}/{{ item }}'
    with_items: '{{ repositories }}'

  - name: Copy .git folder to workspace
    copy: 
      src: '{{ git_dest }}/{{ item }}/.git'
      dest: '{{ workspace  }}/{{ item }}/'
    with_items: '{{ repositories }}'

  - name: Cleanup tmp folder
    file:
      path: '{{ git_dest }}/{{ item }}'
      state: absent
    with_items: '{{ repositories }}'


